MODEL:
  MODEL_NAME: "../models/helmet_yolov3.engine"
  BACKBONE: "ResNet50"
  INPUT_NAME: ["im_shape","image", "scale_factor"]
  OUTPUT_NAMES: [ "multiclass_nms3_0.tmp_0","multiclass_nms3_0.tmp_2"]

DATA:
  VIDEO_NAME: "/home/wgf/Downloads/datasets/Anquanmao/helmet-live/09-38.mp4"
  RTSP_SITE: "" # url to RTSP site.
  INPUT_SHAPE: [1,1,3,1080,1920] # Batch/VideoLen/Channel/Height/Width

PIPELINE:
  STRIDE: 0 # for padding.
  INTERP: 0
  SAMPLE_INTERVAL: 1 # under which we will sample an image.
  TRIGGER_LEN: 1 # trigger a detection
  BATCH_SIZE: 1 # for now only 1 is supported. for video input [B,N,C,H,W] e.g. [1,8,3,320,320]
  THRESHOLD: 0.8
  SCORE_THRESHOLD: 0.6
  TARGET_CLASS: 0 # task dependent. for fight task, 0--no fight, 1--fight.
  ENABLE_SCALE: True
  KEEP_RATIO: True
  TARGET_SIZE: [ 608,608] # e.g.480x640,  height x width
  TRAIN_SIZE: [ 608,608 ] # e.g.480x640,  height x width
  SHORT_SIZE: 340 # short size scale in paddle video.
  PIPELINE_TYPE: [ "TopDownEvalAffine","Resize","LetterBoxResize","NormalizeImage"] # actual pipeline, this should be consistent to class name.
  N_MEAN: [ 0.485, 0.456, 0.406 ] # mean value for each channel in normalization.
  N_STD: [ 0.229, 0.224, 0.225 ] # standard deviation for each channel in normalization
  TIMING: True

POSTPROCESS:
  POST_MODE: 2 # Current 4 types of mode are supported: DRAW_LETTER = 0, DRAW_BOX = 1, DRAW_BOX_LETTER = 2,MASK_OUT = 3
  TEXT_COLOR: [0,0,255] # should be in RGB and value between [0-255]
  ALARM_TEXT_COLOR: [255,0,0]
  BOX_COLOR: [0,0,255] # should be in RGB and value between [0-255]
  ALARM_BOX_COLOR: [255,0,0]
  TEXT_LINE_WIDTH: 2.0 # should be in float
  BOX_LINE_WIDTH: 2 # should be in int
  TEXT_FONT_SIZE: 25 # should be in float
  TEXT_OFF_X: 450 # If negative, we place the x offset to middle of image.
  TEXT_OFF_Y: 50
  POSTPROCESS_NAME: "HelmetDetectionPost"
  POST_TEXT: ["未佩戴安全帽","佩戴安全帽"] #output string literal.
  POST_TEXT_FONT_FILE: "../SIMSUN.ttf"